# Generated by Django 5.0 on 2024-08-31 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaRev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_categoria', models.IntegerField()),
                ('nombre_categoria', models.CharField(max_length=50)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
