# Generated by Django 5.0 on 2024-09-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_categoriarev_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('contraseña', models.CharField(max_length=255)),
                ('rol', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CategoriaRev',
        ),
    ]
