# Generated by Django 4.2 on 2024-12-02 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('rut_empresa', models.BigIntegerField(unique=True)),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id_forma_pago', models.AutoField(primary_key=True, serialize=False)),
                ('metodo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'forma_pago',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.CharField(blank=True, max_length=300, null=True)),
                ('nombre_producto', models.CharField(max_length=200)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('cantidad', models.JSONField()),
                ('precio_compra', models.JSONField()),
                ('porcentaje_de_ganancia', models.JSONField()),
                ('precio_neto', models.JSONField()),
                ('precio_venta', models.JSONField()),
                ('precio_venta_final', models.JSONField()),
                ('codigo_barra', models.BigIntegerField(unique=True)),
                ('descuento', models.JSONField(blank=True, null=True)),
                ('precio_descuento', models.IntegerField(blank=True, null=True)),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.categoria')),
                ('id_empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.empresa')),
            ],
            options={
                'db_table': 'inventario',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_confirmacion', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_usuario', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('id_rol', models.IntegerField()),
                ('id_empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.empresa')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='VentaGeneral',
            fields=[
                ('id_venta_general', models.AutoField(primary_key=True, serialize=False)),
                ('rut_comprador', models.CharField(blank=True, max_length=12, null=True)),
                ('total', models.JSONField()),
                ('fecha_venta', models.DateTimeField()),
                ('id_empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.empresa')),
                ('id_forma_pago', models.ForeignKey(db_column='id_forma_pago', on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.formapago')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.usuario')),
            ],
            options={
                'db_table': 'venta_general',
            },
        ),
        migrations.CreateModel(
            name='VentaProducto',
            fields=[
                ('id_venta_producto', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.JSONField()),
                ('nombre_producto', models.CharField(max_length=200)),
                ('precio_unitario', models.JSONField()),
                ('id_empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.empresa')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.inventario')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.usuario')),
                ('id_venta_general', models.ForeignKey(db_column='id_venta_general', on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.ventageneral')),
            ],
            options={
                'db_table': 'venta_producto',
            },
        ),
        migrations.CreateModel(
            name='HistorialProducto',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=200)),
                ('fecha_modificacion', models.DateTimeField()),
                ('detalle_de_modificacion', models.CharField(blank=True, max_length=200, null=True)),
                ('img', models.CharField(blank=True, max_length=300, null=True)),
                ('nombre_producto', models.CharField(max_length=200)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('cantidad', models.JSONField()),
                ('precio_compra', models.JSONField()),
                ('porcentaje_de_ganancia', models.JSONField()),
                ('precio_neto', models.JSONField()),
                ('precio_venta', models.JSONField()),
                ('precio_venta_final', models.JSONField()),
                ('codigo_barra', models.BigIntegerField(unique=True)),
                ('descuento', models.JSONField(blank=True, null=True)),
                ('precio_descuento', models.IntegerField(blank=True, null=True)),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.categoria')),
                ('id_empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.empresa')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.inventario')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.usuario')),
            ],
            options={
                'db_table': 'historial_producto',
            },
        ),
        migrations.AddField(
            model_name='categoria',
            name='id_empresa',
            field=models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.empresa'),
        ),
    ]
