# Generated by Django 4.2 on 2024-11-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.IntegerField(db_column='Id_categoria', primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(blank=True, db_column='Nombre_categoria', max_length=500, null=True)),
                ('id_empresa', models.IntegerField(blank=True, db_column='Id_empresa', null=True)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.IntegerField(db_column='Id_empresa', primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(blank=True, db_column='Nombre_empresa', max_length=200, null=True)),
            ],
            options={
                'db_table': 'empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id_forma_pago', models.IntegerField(db_column='Id_forma_pago', primary_key=True, serialize=False)),
                ('metodo', models.CharField(blank=True, db_column='Metodo', max_length=200, null=True)),
            ],
            options={
                'db_table': 'forma_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialProducto',
            fields=[
                ('id_historial', models.IntegerField(db_column='Id_historial', primary_key=True, serialize=False)),
                ('id_producto', models.IntegerField(blank=True, db_column='Id_producto', null=True)),
                ('accion', models.CharField(blank=True, db_column='Accion', max_length=200, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, db_column='Fecha_modificacion', null=True)),
                ('detalle_de_modificacion', models.CharField(blank=True, db_column='Detalle_de_modificacion', max_length=200, null=True)),
                ('img', models.IntegerField(blank=True, db_column='Img', null=True)),
                ('nombre_producto', models.CharField(blank=True, db_column='Nombre_producto', max_length=200, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=500, null=True)),
                ('cantidad', models.FloatField(blank=True, db_column='Cantidad', null=True)),
                ('precio_compra', models.FloatField(blank=True, db_column='Precio_compra', null=True)),
                ('porcentaje_de_ganancia', models.FloatField(blank=True, db_column='Porcentaje_de_ganancia', null=True)),
                ('precio_neto', models.FloatField(blank=True, db_column='Precio_neto', null=True)),
                ('precio_venta', models.FloatField(blank=True, db_column='Precio_venta', null=True)),
                ('precio_venta_final', models.CharField(blank=True, db_column='Precio_venta_final', max_length=100, null=True)),
                ('codigo', models.IntegerField(blank=True, db_column='Codigo', null=True)),
                ('id_categoria', models.FloatField(blank=True, db_column='Id_categoria', null=True)),
                ('descuento', models.FloatField(blank=True, db_column='Descuento', null=True)),
                ('precio_descuento', models.FloatField(blank=True, db_column='Precio_descuento', null=True)),
                ('id_empresa', models.IntegerField(blank=True, db_column='Id_empresa', null=True)),
            ],
            options={
                'db_table': 'historial_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.IntegerField(blank=True, db_column='Id_producto', null=True)),
                ('img', models.IntegerField(blank=True, db_column='Img', null=True)),
                ('nombre_producto', models.CharField(blank=True, db_column='Nombre_producto', max_length=200, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=500, null=True)),
                ('cantidad', models.FloatField(blank=True, db_column='Cantidad', null=True)),
                ('precio_compra', models.FloatField(blank=True, db_column='Precio_compra', null=True)),
                ('porcentaje_de_ganancia', models.FloatField(blank=True, db_column='Porcentaje_de_ganancia', null=True)),
                ('precio_neto', models.FloatField(blank=True, db_column='Precio_neto', null=True)),
                ('precio_venta', models.FloatField(blank=True, db_column='Precio_venta', null=True)),
                ('precio_venta_final', models.CharField(blank=True, db_column='Precio_venta_final', max_length=100, null=True)),
                ('codigo', models.IntegerField(blank=True, db_column='Codigo', null=True)),
                ('id_categoria', models.FloatField(blank=True, db_column='Id_categoria', null=True)),
                ('descuento', models.FloatField(blank=True, db_column='Descuento', null=True)),
                ('precio_descuento', models.FloatField(blank=True, db_column='Precio_descuento', null=True)),
                ('id_empresa', models.IntegerField(blank=True, db_column='Id_empresa', null=True)),
            ],
            options={
                'db_table': 'inventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RolUser',
            fields=[
                ('id_rol', models.IntegerField(db_column='Id_rol', primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'rol_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('codigo_vendedor', models.IntegerField(db_column='Codigo_vendedor', primary_key=True, serialize=False)),
                ('id_empresa', models.CharField(blank=True, db_column='Id_empresa', max_length=200, null=True)),
                ('password', models.CharField(blank=True, db_column='Password', max_length=200, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=200, null=True)),
                ('id_rol', models.IntegerField(blank=True, db_column='Id_rol', null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VentaGeneral',
            fields=[
                ('id_venta_total', models.IntegerField(db_column='Id_venta_total', primary_key=True, serialize=False)),
                ('codigo_vendedor', models.CharField(blank=True, db_column='Codigo_vendedor', max_length=200, null=True)),
                ('id_empresa', models.CharField(blank=True, db_column='Id_Empresa', max_length=200, null=True)),
                ('total', models.FloatField(blank=True, db_column='Total', null=True)),
                ('fecha_venta', models.DateTimeField(blank=True, db_column='Fecha_venta', null=True)),
            ],
            options={
                'db_table': 'venta_general',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VentaProducto',
            fields=[
                ('id_venta_producto', models.IntegerField(db_column='Id_venta_producto', primary_key=True, serialize=False)),
                ('id_venta_general', models.IntegerField(blank=True, db_column='Id_venta_general', null=True)),
                ('id_empresa', models.IntegerField(blank=True, db_column='Id_empresa', null=True)),
                ('codigo_vendedor', models.IntegerField(blank=True, db_column='Codigo_vendedor', null=True)),
                ('field_id_producto', models.IntegerField(blank=True, db_column='  id_producto', null=True)),
                ('cantidad', models.IntegerField(blank=True, db_column='Cantidad', null=True)),
                ('nombre_producto', models.CharField(blank=True, db_column='Nombre_producto', max_length=200, null=True)),
                ('precio_unitario', models.FloatField(blank=True, db_column='Precio_unitario', null=True)),
            ],
            options={
                'db_table': 'venta_producto',
                'managed': False,
            },
        ),
    ]
